# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upvote', '0002_auto_20170713_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ip',
        ),
        migrations.AddField(
            model_name='vote',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
