# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upvote', '0003_auto_20170713_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
