# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upvote', '0004_submission_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
