# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upvote', '0006_auto_20170717_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='word',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only letters are allowed.')]),
        ),
    ]
