# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upvote', '0008_submission_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(default='Loomo', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s-]*$', 'Only letters, spaces, and dashes are allowed.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='word',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s-]*$', 'Only letters, spaces, and dashes are allowed.')]),
        ),
    ]
