# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upvote', '0010_auto_20170718_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only letters and spaces are allowed.')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='word',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only letters and spaces are allowed.')]),
        ),
    ]
